In [49]:
!pip3 install kmodes

import random
import string
from collections import defaultdict

import numpy as np
from kmodes.kmodes import KModes
from sklearn.cluster import AgglomerativeClustering
from sklearn.mixture import GaussianMixture


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
def generate_random_dict():
	num_elements = random.randint(32, 128)
	random_dict = {}
	
	keys = np.random.choice(list(string.ascii_lowercase), num_elements)
	for key in keys:
		value = random.uniform(-1, 1)
		random_dict[key] = value
	
	random_dict = dict(sorted(random_dict.items(), key=lambda item: item[1], reverse=True))
	return random_dict


combinations = [generate_random_dict() for _ in range(128)]

In [29]:
data = np.array(list(combinations[0].values())).reshape(-1, 1)

gmm = GaussianMixture(n_components=8, init_params='random')
gmm.fit(data)

gmm_labels = gmm.predict(data)

gmm_predictions = list(zip(data, gmm_labels))

gmm_predictions_dict = defaultdict(list)
for key, value in sorted(gmm_predictions, key=lambda x: x[1]):
	gmm_predictions_dict[value].append(key[0])

gmm_predictions_dict = dict(gmm_predictions_dict)

print(gmm_predictions_dict)

{0: [-0.1753707480539426, -0.419732979093288], 3: [0.9873639878622686], 4: [-0.5716733129990841, -0.6730367198669112, -0.7152887233752461, -0.9086171035630541, -0.908750059758118, -0.9100763468688824], 5: [0.1989521535035239, 0.16366290904746927, 0.14809520521820363, 0.11547249522450853, 0.11046765211185083, 0.009147070755567421], 6: [0.6857375832044912, 0.6363423597958651, 0.471873777674912, 0.4676136984780075, 0.4011503039868194, 0.3227194658662962, 0.2871811452944424, 0.2673744380846659]}


In [30]:
gmm_predictions

[(array([0.98736399]), 3),
 (array([0.68573758]), 6),
 (array([0.63634236]), 6),
 (array([0.47187378]), 6),
 (array([0.4676137]), 6),
 (array([0.4011503]), 6),
 (array([0.32271947]), 6),
 (array([0.28718115]), 6),
 (array([0.26737444]), 6),
 (array([0.19895215]), 5),
 (array([0.16366291]), 5),
 (array([0.14809521]), 5),
 (array([0.1154725]), 5),
 (array([0.11046765]), 5),
 (array([0.00914707]), 5),
 (array([-0.17537075]), 0),
 (array([-0.41973298]), 0),
 (array([-0.57167331]), 4),
 (array([-0.67303672]), 4),
 (array([-0.71528872]), 4),
 (array([-0.9086171]), 4),
 (array([-0.90875006]), 4),
 (array([-0.91007635]), 4)]

In [37]:
agg_clustering = AgglomerativeClustering(n_clusters=3)
agg_clustering.fit(data)

agg_labels = agg_clustering.labels_

gmm_predictions = list(zip(data, agg_labels))

In [38]:
gmm_predictions

[(array([0.98736399]), 2),
 (array([0.68573758]), 2),
 (array([0.63634236]), 2),
 (array([0.47187378]), 1),
 (array([0.4676137]), 1),
 (array([0.4011503]), 1),
 (array([0.32271947]), 1),
 (array([0.28718115]), 1),
 (array([0.26737444]), 1),
 (array([0.19895215]), 1),
 (array([0.16366291]), 1),
 (array([0.14809521]), 1),
 (array([0.1154725]), 1),
 (array([0.11046765]), 1),
 (array([0.00914707]), 1),
 (array([-0.17537075]), 0),
 (array([-0.41973298]), 0),
 (array([-0.57167331]), 0),
 (array([-0.67303672]), 0),
 (array([-0.71528872]), 0),
 (array([-0.9086171]), 0),
 (array([-0.90875006]), 0),
 (array([-0.91007635]), 0)]

In [73]:
data

array([[1, 2, 2, 2],
       [1, 2, 2, 2],
       [1, 1, 1, 1],
       [0, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 4],
       [0, 0, 0, 3],
       [0, 0, 3, 3]])

In [76]:
data = np.array(
		[
				[1, 1, 1, 0, 0, 0, 0, 0],
				[2, 2, 1, 1, 0, 0, 0, 0],
				[2, 2, 1, 1, 0, 0, 0, 3],
				[2, 2, 1, 1, 0, 4, 3, 3]
				]
		).T

k = 4
km = KModes(n_clusters=k, init='Huang', n_init=4, verbose=0)
km_clusters = km.fit_predict(data)

print(km_clusters)

[0 0 2 2 1 3 1 1]


In [ ]:
'''outliers = []
for index, combination in enumerate(combinations):
	outlier = modified_z_score_outliers(combination)
	outlier.extend(tukey_fences_outliers(combination))
	outlier.extend(percentile_based_outliers(combination))
	outlier.extend(mad_outliers(combination))
	outlier.extend(huber_m_outliers(combination))
	
	outlier = Counter(outlier)
	outlier = sorted(outlier.items(), key=lambda item: (-item[1], item[0]))
	outlier = dict(outlier)
	
	positive_outlier = {key: value for key, value in outlier.items() if combination.get(key) > 0}
	negative_outlier = {key: value for key, value in outlier.items() if combination.get(key) < 0}
	
	outliers.append([positive_outlier, negative_outlier])'''